use_frameworks!

target 'EZIdentifiable_Example' do
  pod 'EZIdentifiable', :path => '../'

  target 'EZIdentifiable_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
